### ISSUE TITLE
Email id not getting read post request add user 

### ISSUE THREAD

**Issue by Akilan1999** [Sifr-Labs-2020-Interns/IOE-electricity-cost#7]
When doing a post request with postman the email_id does not get stored in the DB for add user

**Comment by wgb-10** [comment]
I think I fixed this issue. This strangely happened because of a space between "form:" and "email_id" in the definitions of the NewUser and RemoveUser structs. The following image shows the lines that have been fixed.

![image](https://user-images.githubusercontent.com/55624355/85840360-6a5e1f80-b7ad-11ea-8790-761115996e06.png)

**Comment by Akilan1999** [comment]
Great job fixed
